spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_management
spring.datasource.username=roshanhingnekar
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false